language: php

php:
  - 17.4.10

cache: npm

install: composer install

script: php vendor/bin/phpunit

deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master

