language: php
php:
  - 7.1.9

cache: npm

install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
script: php vendor/bin/phpunit
services:
  - mysql
deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master

