language: php
php:
  - 7.1.9

cache: npm

install:
  - ./bin/ci/install_dependencies.sh
  - php vendor/vendors.php
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
script: php vendor/bin/phpunit

deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master

