language: php
php:
  - 7.2
warnings_are_errors: false
cache: npm
sudo: false
install:
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
script: php vendor/bin/phpunit
services:
  - mysql
deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master

